/*
	*	Original script by: Shafiul Azam
	*	Version 4.0
	*	Modified by: Luigi Balzano
	*	Version 4.1 - 25 nov 2015
	*	Added the country and state code as option value. Now the <option> tag
	*	has th following format:
	*	<option value=[country_state_code]>[country_state_label]</option>
	*	Modified by: Roberto Peruzzo <roberto.peruzzo@studioaqua.it>

	*	Description:
	*	Inserts Countries and/or States as Dropdown List
	*	How to Use:

		In Head section:
		----------------
		<script type= "text/javascript" src = "countries.js"></script>

		In Body Section:
		----------------
		Select Country (with states):   <select id="country" name ="country"></select>

		Select State: <select name ="state" id ="state"></select>

        Select Country (without states):   <select id="country2" name ="country2"></select>

		<script language="javascript">
			populateCountries("country",
  "state");
			populateCountries("country2");
		</script>

	*
	*	License: Free to copy, distribute, modify, whatever you want to.
	*	Aurthor's Website: http://bdhacker.wordpress.com
	*
*/

// Countries
var country_arr = [
	{code:"AF", label:"Afghanistan"},
	{code:"AX", label:"Aland Islands"},
	{code:"AL", label:"Albania"},
	{code:"DZ", label:"Algeria"},
	{code:"AD", label:"Andorra"},
	{code:"AO", label:"Angola"},
	{code:"AI", label:"Anguilla"},
	{code:"AQ", label:"Antarctica"},
	{code:"AG", label:"Antigua and Barbuda"},
	{code:"AR", label:"Argentina"},
	{code:"AM", label:"Armenia"},
	{code:"AW", label:"Aruba"},
	{code:"AU", label:"Australia"},
	{code:"AT", label:"Austria"},
	{code:"AZ", label:"Azerbaijan"},
	{code:"BS", label:"Bahamas"},
	{code:"BH", label:"Bahrain"},
	{code:"BD", label:"Bangladesh"},
	{code:"BB", label:"Barbados"},
	{code:"BY", label:"Belarus"},
	{code:"BE", label:"Belgium"},
	{code:"BZ", label:"Belize"},
	{code:"BJ", label:"Benin"},
	{code:"BM", label:"Bermuda"},
	{code:"BT", label:"Bhutan"},
	{code:"BO", label:"Bolivia, Plurinational State of"},
	{code:"BQ", label:"Bonaire, Sint Eustatius and Saba"},
	{code:"BA", label:"Bosnia and Herzegovina"},
	{code:"BW", label:"Botswana"},
	{code:"BV", label:"Bouvet Island"},
	{code:"BR", label:"Brazil"},
	{code:"IO", label:"British Indian Ocean Territory"},
	{code:"BN", label:"Brunei Darussalam"},
	{code:"BG", label:"Bulgaria"},
	{code:"BF", label:"Burkina Faso"},
	{code:"BI", label:"Burundi"},
	{code:"KH", label:"Cambodia"},
	{code:"CM", label:"Cameroon"},
	{code:"CA", label:"Canada"},
	{code:"CV", label:"Cape Verde"},
	{code:"KY", label:"Cayman Islands"},
	{code:"CF", label:"Central African Republic"},
	{code:"TD", label:"Chad"},
	{code:"CL", label:"Chile"},
	{code:"CN", label:"China"},
	{code:"TW", label:"Chinese Taipei"},
	{code:"CX", label:"Christmas Island"},
	{code:"CC", label:"Cocos (Keeling} Islands"},
	{code:"CO", label:"Colombia"},
	{code:"KM", label:"Comoros"},
	{code:"CG", label:"Congo"},
	{code:"CD", label:"Congo, the Democratic Republic of the"},
	{code:"CK", label:"Cook Islands"},
	{code:"CR", label:"Costa Rica"},
	{code:"CI", label:"Cote d&#39;Ivoire"},
	{code:"HR", label:"Croatia"},
	{code:"CU", label:"Cuba"},
	{code:"CW", label:"Curaçao"},
	{code:"CY", label:"Cyprus"},
	{code:"CZ", label:"Czech Republic"},
	{code:"DK", label:"Denmark"},
	{code:"DJ", label:"Djibouti"},
	{code:"DM", label:"Dominica"},
	{code:"DO", label:"Dominican Republic"},
	{code:"EC", label:"Ecuador"},
	{code:"EG", label:"Egypt"},
	{code:"SV", label:"El Salvador"},
	{code:"GQ", label:"Equatorial Guinea"},
	{code:"ER", label:"Eritrea"},
	{code:"EE", label:"Estonia"},
	{code:"ET", label:"Ethiopia"},
	{code:"FK", label:"Falkland Islands (Malvinas}"},
	{code:"FO", label:"Faroe Islands"},
	{code:"FJ", label:"Fiji"},
	{code:"FI", label:"Finland"},
	{code:"FR", label:"France"},
	{code:"GF", label:"French Guiana"},
	{code:"PF", label:"French Polynesia"},
	{code:"TF", label:"French Southern Territories"},
	{code:"GA", label:"Gabon"},
	{code:"GM", label:"Gambia"},
	{code:"GE", label:"Georgia"},
	{code:"DE", label:"Germany"},
	{code:"GH", label:"Ghana"},
	{code:"GI", label:"Gibraltar"},
	{code:"GR", label:"Greece"},
	{code:"GL", label:"Greenland"},
	{code:"GD", label:"Grenada"},
	{code:"GP", label:"Guadeloupe"},
	{code:"GT", label:"Guatemala"},
	{code:"GG", label:"Guernsey"},
	{code:"GN", label:"Guinea"},
	{code:"GW", label:"Guinea-Bissau"},
	{code:"GY", label:"Guyana"},
	{code:"HT", label:"Haiti"},
	{code:"HM", label:"Heard Island and McDonald Islands"},
	{code:"VA", label:"Holy See (Vatican City State}"},
	{code:"HN", label:"Honduras"},
	{code:"HU", label:"Hungary"},
	{code:"IS", label:"Iceland"},
	{code:"IN", label:"India"},
	{code:"ID", label:"Indonesia"},
	{code:"IR", label:"Iran, Islamic Republic of"},
	{code:"IQ", label:"Iraq"},
	{code:"IE", label:"Ireland"},
	{code:"IM", label:"Isle of Man"},
	{code:"IL", label:"Israel"},
	{code:"IT", label:"Italy"},
	{code:"JM", label:"Jamaica"},
	{code:"JP", label:"Japan"},
	{code:"JE", label:"Jersey"},
	{code:"JO", label:"Jordan"},
	{code:"KZ", label:"Kazakhstan"},
	{code:"KE", label:"Kenya"},
	{code:"KI", label:"Kiribati"},
	{code:"KP", label:"Korea, Democratic People&#39;s Republic of"},
	{code:"KR", label:"Korea, Republic of"},
	{code:"KW", label:"Kuwait"},
	{code:"KG", label:"Kyrgyzstan"},
	{code:"LA", label:"Lao People&#39;s Democratic Republic"},
	{code:"LV", label:"Latvia"},
	{code:"LB", label:"Lebanon"},
	{code:"LS", label:"Lesotho"},
	{code:"LR", label:"Liberia"},
	{code:"LY", label:"Libyan Arab Jamahiriya"},
	{code:"LI", label:"Liechtenstein"},
	{code:"LT", label:"Lithuania"},
	{code:"LU", label:"Luxembourg"},
	{code:"MO", label:"Macao"},
	{code:"MK", label:"Macedonia, the former Yugoslav Republic of"},
	{code:"MG", label:"Madagascar"},
	{code:"MW", label:"Malawi"},
	{code:"MY", label:"Malaysia"},
	{code:"MV", label:"Maldives"},
	{code:"ML", label:"Mali"},
	{code:"MT", label:"Malta"},
	{code:"MQ", label:"Martinique"},
	{code:"MR", label:"Mauritania"},
	{code:"MU", label:"Mauritius"},
	{code:"YT", label:"Mayotte"},
	{code:"MX", label:"Mexico"},
	{code:"MD", label:"Moldova, Republic of"},
	{code:"MC", label:"Monaco"},
	{code:"MN", label:"Mongolia"},
	{code:"ME", label:"Montenegro"},
	{code:"MS", label:"Montserrat"},
	{code:"MA", label:"Morocco"},
	{code:"MZ", label:"Mozambique"},
	{code:"MM", label:"Myanmar"},
	{code:"NA", label:"Namibia"},
	{code:"NR", label:"Nauru"},
	{code:"NP", label:"Nepal"},
	{code:"NL", label:"Netherlands"},
	{code:"NC", label:"New Caledonia"},
	{code:"NZ", label:"New Zealand"},
	{code:"NI", label:"Nicaragua"},
	{code:"NE", label:"Niger"},
	{code:"NG", label:"Nigeria"},
	{code:"NU", label:"Niue"},
	{code:"NF", label:"Norfolk Island"},
	{code:"NO", label:"Norway"},
	{code:"OM", label:"Oman"},
	{code:"PK", label:"Pakistan"},
	{code:"PS", label:"Palestinian Territory, Occupied"},
	{code:"PA", label:"Panama"},
	{code:"PG", label:"Papua New Guinea"},
	{code:"PY", label:"Paraguay"},
	{code:"PE", label:"Peru"},
	{code:"PH", label:"Philippines"},
	{code:"PN", label:"Pitcairn"},
	{code:"PL", label:"Poland"},
	{code:"PT", label:"Portugal"},
	{code:"QA", label:"Qatar"},
	{code:"RE", label:"Reunion"},
	{code:"RO", label:"Romania"},
	{code:"RU", label:"Russian Federation"},
	{code:"RW", label:"Rwanda"},
	{code:"BL", label:"Saint Barthélemy"},
	{code:"SH", label:"Saint Helena, Ascension and Tristan da Cunha"},
	{code:"KN", label:"Saint Kitts and Nevis"},
	{code:"LC", label:"Saint Lucia"},
	{code:"MF", label:"Saint Martin (French part}"},
	{code:"PM", label:"Saint Pierre and Miquelon"},
	{code:"VC", label:"Saint Vincent and the Grenadines"},
	{code:"WS", label:"Samoa"},
	{code:"SM", label:"San Marino"},
	{code:"ST", label:"Sao Tome and Principe"},
	{code:"SA", label:"Saudi Arabia"},
	{code:"SN", label:"Senegal"},
	{code:"RS", label:"Serbia"},
	{code:"SC", label:"Seychelles"},
	{code:"SL", label:"Sierra Leone"},
	{code:"SG", label:"Singapore"},
	{code:"SX", label:"Sint Maarten (Dutch part}"},
	{code:"SK", label:"Slovakia"},
	{code:"SI", label:"Slovenia"},
	{code:"SB", label:"Solomon Islands"},
	{code:"SO", label:"Somalia"},
	{code:"ZA", label:"South Africa"},
	{code:"GS", label:"South Georgia and the South Sandwich Islands"},
	{code:"SS", label:"South Sudan"},
	{code:"ES", label:"Spain"},
	{code:"LK", label:"Sri Lanka"},
	{code:"SD", label:"Sudan"},
	{code:"SR", label:"Suriname"},
	{code:"SJ", label:"Svalbard and Jan Mayen"},
	{code:"SZ", label:"Swaziland"},
	{code:"SE", label:"Sweden"},
	{code:"CH", label:"Switzerland"},
	{code:"SY", label:"Syrian Arab Republic"},
	{code:"TJ", label:"Tajikistan"},
	{code:"TZ", label:"Tanzania, United Republic of"},
	{code:"TH", label:"Thailand"},
	{code:"TL", label:"Timor-Leste"},
	{code:"TG", label:"Togo"},
	{code:"TK", label:"Tokelau"},
	{code:"TO", label:"Tonga"},
	{code:"TT", label:"Trinidad and Tobago"},
	{code:"TN", label:"Tunisia"},
	{code:"TR", label:"Turkey"},
	{code:"TM", label:"Turkmenistan"},
	{code:"TC", label:"Turks and Caicos Islands"},
	{code:"TV", label:"Tuvalu"},
	{code:"UG", label:"Uganda"},
	{code:"UA", label:"Ukraine"},
	{code:"AE", label:"United Arab Emirates"},
	{code:"GB", label:"United Kingdom"},
	{code:"US", label:"United States"},
	{code:"UY", label:"Uruguay"},
	{code:"UZ", label:"Uzbekistan"},
	{code:"VU", label:"Vanuatu"},
	{code:"VE", label:"Venezuela, Bolivarian Republic of"},
	{code:"VN", label:"Viet Nam"},
	{code:"VG", label:"Virgin Islands, British"},
	{code:"WF", label:"Wallis and Futuna"},
	{code:"EH", label:"Western Sahara"},
	{code:"YE", label:"Yemen"},
	{code:"ZM", label:"Zambia"},
	{code:"ZW", label:"Zimbabwe"}
];

// States
var all_states = {
	AF: [],
	AX: [],
	AL: [],
	DZ: [],
	AD: [],
	AO: [],
	AI: [],
	AQ: [],
	AG: [],
	AR: [],
	AM: [],
	AW: [],
	AU: [
		{code:"ACT", label:"Australian Capital Territory"}
	],
	AT: [],
	AZ: [],
	BS: [],
	BH: [],
	BD: [],
	BB: [],
	BY: [],
	BE: [],
	BZ: [],
	BJ: [],
	BM: [],
	BT: [],
	BO: [],
	BQ: [],
	BA: [],
	BW: [],
	BV: [],
	BR: [
		{code:"AC", label:"Acre"},
		{code:"AL", label:"Alagoas"},
		{code:"AP", label:"Amapá"},
		{code:"AM", label:"Amazonas"},
		{code:"BA", label:"Bahia"},
		{code:"CE", label:"Ceará"}
	],
	IO: [],
	BN: [],
	BG: [],
	BF: [],
	BI: [],
	KH: [],
	CM: [],
	CA: [
		{code:"AB", label:"Alberta"},
		{code:"BC", label:"British Columbia"},
		{code:"MB", label:"Manitoba"},
		{code:"NB", label:"New Brunswick"},
		{code:"NL", label:"Newfoundland and Labrador"},
		{code:"NT", label:"Northwest Territories"},
		{code:"NS", label:"Nova Scotia"},
		{code:"NU", label:"Nunavut"},
		{code:"ON", label:"Ontario"},
		{code:"PE", label:"Prince Edward Island"},
		{code:"QC", label:"Quebec"},
		{code:"SK", label:"Saskatchewan"},
		{code:"YT", label:"Yukon Territories"}
	],
	CV: [],
	KY: [],
	CF: [],
	TD: [],
	CL: [],
	CN: [
		{code:"34", label:"Anhui"},
		{code:"11", label:"Beijing"},
		{code:"71", label:"Chinese Taipei"},
		{code:"50", label:"Chongqing"}

	],
	TW: [],
	CX: [],
	CC: [],
	CO: [],
	KM: [],
	CG: [],
	CD: [],
	CK: [],
	CR: [],
	CI: [],
	HR: [],
	CU: [],
	CW: [],
	CY: [],
	CZ: [],
	DK: [],
	DJ: [],
	DM: [],
	DO: [],
	EC: [],
	EG: [],
	SV: [],
	GQ: [],
	ER: [],
	EE: [],
	ET: [],
	FK: [],
	FO: [],
	FJ: [],
	FI: [],
	FR: [],
	GF: [],
	PF: [],
	TF: [],
	GA: [],
	GM: [],
	GE: [],
	DE: [],
	GH: [],
	GI: [],
	GR: [],
	GL: [],
	GD: [],
	GP: [],
	GT: [],
	GG: [],
	GN: [],
	GW: [],
	GY: [],
	HT: [],
	HM: [],
	VA: [],
	HN: [],
	HU: [],
	IS: [],
	IN: [
		{code:"AN", label:"Andaman and Nicobar Islands"},
		{code:"AP", label:"Andhra Pradesh"},
		{code:"AR", label:"Arunachal Pradesh"},
		{code:"AS", label:"Assam"},
		{code:"BR", label:"Bihar"},
		{code:"CH", label:"Chandigarh"},
		{code:"CT", label:"Chhattisgarh"}
	],
	ID: [],
	IR: [],
	IQ: [],
	IE: [
		{code:"CW", label:"Carlow"},
		{code:"CN", label:"Cavan"},
		{code:"CE", label:"Clare"},
		{code:"CO", label:"Cork"}
	],
	IM: [],
	IL: [],
	IT: [
		{code:"AG", label:"Agrigento"},
		{code:"AL", label:"Alessandria"},
		{code:"AN", label:"Ancona"},
		{code:"AO", label:"Aosta"},
		{code:"AR", label:"Arezzo"},
		{code:"AP", label:"Ascoli Piceno"},
		{code:"AT", label:"Asti"},
		{code:"AV", label:"Avellino"},
		{code:"BA", label:"Bari"},
		{code:"BT", label:"Barletta-Andria-Trani"},
		{code:"BL", label:"Belluno"},
		{code:"BN", label:"Benevento"},
		{code:"BG", label:"Bergamo"},
		{code:"BI", label:"Biella"},
		{code:"BO", label:"Bologna"},
		{code:"BZ", label:"Bolzano"},
		{code:"BS", label:"Brescia"},
		{code:"BR", label:"Brindisi"},
		{code:"CA", label:"Cagliari"},
		{code:"CL", label:"Caltanissetta"},
		{code:"CB", label:"Campobasso"},
		{code:"CI", label:"Carbonia-Iglesias"},
		{code:"CE", label:"Caserta"},
		{code:"CT", label:"Catania"},
		{code:"CZ", label:"Catanzaro"},
		{code:"CH", label:"Chieti"},
		{code:"CO", label:"Como"},
		{code:"CS", label:"Cosenza"},
		{code:"CR", label:"Cremona"},
		{code:"KR", label:"Crotone"},
		{code:"CN", label:"Cuneo"}
	],
	JM: [],
	JP: [],
	JE: [],
	JO: [],
	KZ: [],
	KE: [],
	KI: [],
	KP: [],
	KR: [],
	KW: [],
	KG: [],
	LA: [],
	LV: [],
	LB: [],
	LS: [],
	LR: [],
	LY: [],
	LI: [],
	LT: [],
	LU: [],
	MO: [],
	MK: [],
	MG: [],
	MW: [],
	MY: [],
	MV: [],
	ML: [],
	MT: [],
	MQ: [],
	MR: [],
	MU: [],
	YT: [],
	MX: [
		{code:"AG", label:"Aguascalientes"},
		{code:"BC", label:"Baja California"},
		{code:"BS", label:"Baja California Sur"},
		{code:"CM", label:"Campeche"},
		{code:"CS", label:"Chiapas"},
		{code:"CH", label:"Chihuahua"},
		{code:"CO", label:"Coahuila"},
		{code:"CL", label:"Colima"}
	],
	MD: [],
	MC: [],
	MN: [],
	ME: [],
	MS: [],
	MA: [],
	MZ: [],
	MM: [],
	NA: [],
	NR: [],
	NP: [],
	NL: [],
	NC: [],
	NZ: [],
	NI: [],
	NE: [],
	NG: [],
	NU: [],
	NF: [],
	NO: [],
	OM: [],
	PK: [],
	PS: [],
	PA: [],
	PG: [],
	PY: [],
	PE: [],
	PH: [],
	PN: [],
	PL: [],
	PT: [],
	QA: [],
	RE: [],
	RO: [],
	RU: [],
	RW: [],
	BL: [],
	SH: [],
	KN: [],
	LC: [],
	MF: [],
	PM: [],
	VC: [],
	WS: [],
	SM: [],
	ST: [],
	SA: [],
	SN: [],
	RS: [],
	SC: [],
	SL: [],
	SG: [],
	SX: [],
	SK: [],
	SI: [],
	SB: [],
	SO: [],
	ZA: [],
	GS: [],
	SS: [],
	ES: [],
	LK: [],
	SD: [],
	SR: [],
	SJ: [],
	SZ: [],
	SE: [],
	CH: [],
	SY: [],
	TJ: [],
	TZ: [],
	TH: [],
	TL: [],
	TG: [],
	TK: [],
	TO: [],
	TT: [],
	TN: [],
	TR: [],
	TM: [],
	TC: [],
	TV: [],
	UG: [],
	UA: [],
	AE: [],
	GB: [],
	US: [
		{code:"AL", label:"Alabama"},
		{code:"AK", label:"Alaska"},
		{code:"AZ", label:"Arizona"},
		{code:"AR", label:"Arkansas"},
		{code:"CA", label:"California"},
		{code:"CO", label:"Colorado"},
		{code:"CT", label:"Connecticut"},
		{code:"DE", label:"Delaware"},
		{code:"DC", label:"District of Columbia"},
		{code:"FL", label:"Florida"},
		{code:"GA", label:"Georgia"},
		{code:"GU", label:"Guam"},
		{code:"HI", label:"Hawaii"},
		{code:"ID", label:"Idaho"},
		{code:"IL", label:"Illinois"},
		{code:"IN", label:"Indiana"},
		{code:"IA", label:"Iowa"},
		{code:"KS", label:"Kansas"},
		{code:"KY", label:"Kentucky"},
		{code:"LA", label:"Louisiana"},
		{code:"ME", label:"Maine"},
		{code:"MD", label:"Maryland"},
		{code:"MA", label:"Massachusetts"},
		{code:"MI", label:"Michigan"},
		{code:"MN", label:"Minnesota"},
		{code:"MS", label:"Mississippi"},
		{code:"MO", label:"Missouri"},
		{code:"MT", label:"Montana"},
		{code:"NE", label:"Nebraska"},
		{code:"NV", label:"Nevada"},
		{code:"NH", label:"New Hampshire"},
		{code:"NJ", label:"New Jersey"},
		{code:"NM", label:"New Mexico"},
		{code:"NY", label:"New York"},
		{code:"NC", label:"North Carolina"},
		{code:"ND", label:"North Dakota"},
		{code:"OH", label:"Ohio"},
		{code:"OK", label:"Oklahoma"},
		{code:"OR", label:"Oregon"},
		{code:"PA", label:"Pennsylvania"},
		{code:"PR", label:"Puerto Rico"},
		{code:"RI", label:"Rhode Island"},
		{code:"SC", label:"South Carolina"},
		{code:"SD", label:"South Dakota"},
		{code:"TN", label:"Tennessee"},
		{code:"TX", label:"Texas"},
		{code:"VI", label:"US Virgin Islands"},
		{code:"UT", label:"Utah"},
		{code:"VT", label:"Vermont"},
		{code:"VA", label:"Virginia"},
		{code:"WA", label:"Washington"},
		{code:"WV", label:"West Virginia"},
		{code:"WI", label:"Wisconsin"},
		{code:"WY", label:"Wyoming"}
	],
	UY: [],
	UZ: [],
	VU: [],
	VE: [],
	VN: [],
	VG: [],
	WF: [],
	EH: [],
	YE: [],
	ZM: [],
	ZW: []
};


function populateStates( countryElementId, stateElementId ){

	var element = document.getElementById( countryElementId );
	var selectedCountryCode = element.options[element.selectedIndex].value;

	// Init the first option element.
	var stateElement = document.getElementById( stateElementId );
	stateElement.length = 0;	// Fixed by Julian Woods
	stateElement.options[0] = new Option('Select State or Province','');
	stateElement.selectedIndex = 0;

	var state_arr = all_states[selectedCountryCode];

	for (var i=0; i<state_arr.length; i++) {
		stateElement.options[i+1] = new Option(
			state_arr[i].label,
			state_arr[i].code);
	}
}

function populateCountries(countryElementId, stateElementId){
	// given the id of the <select> tag as function argument, it inserts <option> tags
	var countryElement = document.getElementById(countryElementId);
	countryElement.length=0;
	countryElement.options[0] = new Option('Select Country','-1');
	countryElement.selectedIndex = 0;
	for (var i=0; i<country_arr.length; i++) {
		countryElement.options[countryElement.length] = new Option(
			country_arr[i].label,
			country_arr[i].code);
	}

	// Assigned all countries. Now assign event listener for the states.

	if( stateElementId ){
		countryElement.onchange = function(){
			populateStates( countryElementId, stateElementId );
		};
	}
}
